# Generated by Django 3.0.5 on 2020-05-29 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('pubg_id', models.IntegerField(blank=True, null=True)),
                ('pubg_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('google_pay', 'Google Pay'), ('paytm', 'Paytm')], max_length=20, null=True)),
                ('acc_num', models.CharField(blank=True, max_length=50, null=True)),
                ('ifscode', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('team_type', models.CharField(blank=True, choices=[('solo', 'Solo'), ('duo', 'Duo'), ('squad', 'Squad')], max_length=10, null=True)),
                ('room_id', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_charge', models.IntegerField(blank=True, null=True)),
                ('win_prize', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PubgTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('team_type', models.CharField(blank=True, choices=[('solo', 'Solo'), ('duo', 'Duo'), ('squad', 'Squad')], max_length=10, null=True)),
                ('player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_player_1', to='mainapp.Gamer')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_player_2', to='mainapp.Gamer')),
                ('player_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_player_3', to='mainapp.Gamer')),
                ('player_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_player_4', to='mainapp.Gamer')),
            ],
        ),
    ]
