# Generated by Django 3.0.5 on 2020-06-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionDev',
            new_name='SessionDeveloper',
        ),
    ]
