# Generated by Django 3.0.5 on 2020-05-22 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'blood_group',
            },
        ),
        migrations.CreateModel(
            name='BloodIssue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blood_issue',
            },
        ),
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_long', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('unit_a_pos', models.IntegerField(blank=True, null=True)),
                ('unit_b_pos', models.IntegerField(blank=True, null=True)),
                ('unit_o_pos', models.IntegerField(blank=True, null=True)),
                ('unit_ab_pos', models.IntegerField(blank=True, null=True)),
                ('unit_a_neg', models.IntegerField(blank=True, null=True)),
                ('unit_b_neg', models.IntegerField(blank=True, null=True)),
                ('unit_o_neg', models.IntegerField(blank=True, null=True)),
                ('unit_ab_neg', models.IntegerField(blank=True, null=True)),
                ('total_donors', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camp',
            },
        ),
        migrations.CreateModel(
            name='IdProof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proof_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'id_proof',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('min_units', models.IntegerField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.BloodGroup')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, max_length=30, null=True)),
                ('blood_group', models.IntegerField(blank=True, null=True)),
                ('id_proof', models.ForeignKey(blank=True, db_column='id_proof', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.IdProof')),
            ],
            options={
                'db_table': 'donor',
            },
        ),
        migrations.CreateModel(
            name='BloodUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_abo', models.IntegerField(blank=True, null=True)),
                ('test_rh', models.IntegerField(blank=True, null=True)),
                ('test_antibody', models.IntegerField(blank=True, null=True)),
                ('test_hep_b', models.IntegerField(blank=True, null=True)),
                ('test_hep_c', models.IntegerField(blank=True, null=True)),
                ('test_alt', models.IntegerField(blank=True, null=True)),
                ('test_htlv', models.IntegerField(blank=True, null=True)),
                ('test_hiv', models.IntegerField(blank=True, null=True)),
                ('test_passed', models.IntegerField(blank=True, null=True)),
                ('donor', models.ForeignKey(blank=True, db_column='donor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Donor')),
                ('group', models.ForeignKey(blank=True, db_column='group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.BloodGroup')),
            ],
            options={
                'db_table': 'blood_unit',
            },
        ),
    ]
