# Generated by Django 3.0.5 on 2020-05-22 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-'), ('AB-', 'AB-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='bloodissue',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.BloodGroup'),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Donor'),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.BloodGroup'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='id_proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.IdProof'),
        ),
        migrations.AlterModelTable(
            name='bloodgroup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bloodissue',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bloodunit',
            table=None,
        ),
        migrations.AlterModelTable(
            name='camp',
            table=None,
        ),
        migrations.AlterModelTable(
            name='donor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='idproof',
            table=None,
        ),
        migrations.AlterModelTable(
            name='inventory',
            table=None,
        ),
    ]
