# Generated by Django 3.0.5 on 2020-05-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200523_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodissue',
            name='buyer',
            field=models.CharField(blank=True, choices=[('Person', 'Person'), ('Hospital', 'Hospital')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='test_abo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='test_alt',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='test_antibody',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='test_hep_b',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='test_hep_c',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='test_hiv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='test_htlv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='test_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='test_rh',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.BloodGroup'),
        ),
    ]
