# Generated by Django 3.0.5 on 2020-05-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_profile',
            },
        ),
        migrations.CreateModel(
            name='ImageStore',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('thumb_image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_store',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ForeignKey(blank=True, db_column='profile_image', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.ImageProfile')),
                ('subscription', models.ForeignKey(blank=True, db_column='subscription', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Subscription')),
            ],
            options={
                'db_table': 'studio',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Country')),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True)),
                ('location_long', models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True)),
                ('city', models.ForeignKey(blank=True, db_column='city', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.City')),
                ('country', models.ForeignKey(blank=True, db_column='country', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Country')),
                ('state', models.ForeignKey(blank=True, db_column='state', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.State')),
                ('studio', models.ForeignKey(blank=True, db_column='studio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Studio')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('long_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('expirience', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('applicants', models.IntegerField(blank=True, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.ForeignKey(blank=True, db_column='location', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Location')),
                ('studio', models.ForeignKey(blank=True, db_column='studio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Studio')),
            ],
            options={
                'db_table': 'job_listing',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('artist', models.ForeignKey(blank=True, db_column='artist', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Artist')),
                ('job_listing', models.ForeignKey(blank=True, db_column='job_listing', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.JobListing')),
            ],
            options={
                'db_table': 'job_application',
            },
        ),
        migrations.CreateModel(
            name='ImageInfoStudio',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('medium', models.CharField(blank=True, max_length=255, null=True)),
                ('software', models.CharField(blank=True, max_length=255, null=True)),
                ('image_store', models.ForeignKey(blank=True, db_column='image_store', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.ImageStore')),
                ('owner', models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Studio')),
            ],
            options={
                'db_table': 'image_info_studio',
            },
        ),
        migrations.CreateModel(
            name='ImageInfoArtist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
                ('medium', models.CharField(blank=True, max_length=255, null=True)),
                ('software', models.CharField(blank=True, max_length=255, null=True)),
                ('image_store', models.ForeignKey(blank=True, db_column='image_store', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.ImageStore')),
                ('owner', models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Artist')),
            ],
            options={
                'db_table': 'image_info_artist',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, db_column='state', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.State'),
        ),
        migrations.AddField(
            model_name='artist',
            name='subscription',
            field=models.ForeignKey(blank=True, db_column='subscription', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Subscription'),
        ),
    ]
