# Generated by Django 3.0.5 on 2020-05-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMainStore',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artist_image')),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'image_main_store',
            },
        ),
    ]
