# Generated by Django 3.0.5 on 2020-06-02 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activesession',
            name='session_type',
        ),
        migrations.RemoveField(
            model_name='activesession',
            name='studio',
        ),
        migrations.CreateModel(
            name='ActiveStudioSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Studio')),
            ],
        ),
    ]
