# Generated by Django 3.0.5 on 2020-05-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_imagemainstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemainstore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
