# Generated by Django 3.0.5 on 2020-05-28 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200529_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='short_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='joblisting',
            old_name='expirience',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='applicants',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='location',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='long_desc',
        ),
    ]
