# Generated by Django 3.0.5 on 2020-06-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200529_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageinfoartist',
            name='image_store',
        ),
        migrations.RemoveField(
            model_name='imageinfoartist',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='imageinfoartist',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='imageinfoartist',
            name='software',
        ),
        migrations.AddField(
            model_name='imageprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Artist'),
        ),
        migrations.AddField(
            model_name='imagestore',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagestore',
            name='medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagestore',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Artist'),
        ),
        migrations.AddField(
            model_name='imagestore',
            name='software',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
