# Generated by Django 3.0.5 on 2020-06-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200601_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagestore',
            name='thumb_image',
        ),
    ]
