# Generated by Django 3.0.5 on 2020-05-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('gstin', models.CharField(blank=True, db_column='GSTIN', max_length=15, null=True)),
                ('primary_location', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=21, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, max_length=140, null=True)),
                ('long_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('laptops', 'Laptop'), ('clothing', 'Clothing'), ('food', 'Food')], max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('customer', models.ForeignKey(blank=True, db_column='customer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.Customer')),
            ],
        ),
    ]
